# Generated by Django 4.2.17 on 2025-02-09 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shipper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('mobile_number', models.CharField(max_length=20)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=20, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('receiver_name', models.CharField(max_length=100)),
                ('receiver_contact_person', models.CharField(max_length=100)),
                ('receiver_contact_number', models.CharField(max_length=20)),
                ('receiver_mobile_number', models.CharField(max_length=20)),
                ('product_type', models.CharField(max_length=100)),
                ('pieces', models.PositiveIntegerField()),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('item_description', models.TextField()),
                ('receiver_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver_shipments', to='shipments.address')),
                ('shipper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shipments.shipper')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='shipments.country')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.city'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.country'),
        ),
    ]
