# Generated by Django 4.2.17 on 2025-02-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awb_number', models.CharField(max_length=50, unique=True)),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('shipper', models.CharField(max_length=100)),
                ('shipper_address', models.TextField()),
                ('shipper_country', models.CharField(max_length=50)),
                ('shipper_city', models.CharField(max_length=50)),
                ('shipper_location', models.CharField(blank=True, max_length=100, null=True)),
                ('shipper_contact_person', models.CharField(max_length=100)),
                ('shipper_contact_number', models.CharField(max_length=20)),
                ('shipper_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('product_type', models.CharField(max_length=50)),
                ('pieces', models.PositiveIntegerField()),
                ('special_instruction', models.TextField(blank=True, null=True)),
                ('booking_date', models.DateField()),
                ('booking_time', models.TimeField()),
                ('receiver', models.CharField(max_length=100)),
                ('receiver_address', models.TextField()),
                ('receiver_country', models.CharField(max_length=50)),
                ('receiver_city', models.CharField(max_length=50)),
                ('receiver_location', models.CharField(blank=True, max_length=100, null=True)),
                ('receiver_contact_person', models.CharField(max_length=100)),
                ('receiver_contact_number', models.CharField(max_length=20)),
                ('receiver_mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('v_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('c_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cod_amount', models.DecimalField(decimal_places=2, help_text='COD in AED', max_digits=10)),
                ('item_description', models.TextField()),
            ],
        ),
    ]
