# Generated by Django 4.2.20 on 2025-06-04 14:38

from django.db import migrations, models
import shipments.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='chargeable_weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[shipments.models.zip_code_validator]),
        ),
        migrations.AddField(
            model_name='shipper',
            name='identity_image',
            field=models.ImageField(blank=True, help_text='Upload a copy of your ID or passport', null=True, upload_to='shipper_identity/'),
        ),
        migrations.AddField(
            model_name='shipper',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[shipments.models.zip_code_validator]),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='awb_number',
            field=models.CharField(default='0', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='cod_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='COD in AED', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='forwarder',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reference_number',
            field=models.CharField(blank=True, default='0', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volumetricks',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipmentimage',
            name='image',
            field=models.ImageField(upload_to='shipment_images/', validators=[shipments.models.validate_image_file, shipments.models.validate_image_file_size]),
        ),
    ]
