# Generated by Django 4.2.20 on 2025-05-24 15:03

from django.db import migrations, models
import shipments.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='chargeable_weight',
            field=models.DecimalField(decimal_places=2, default=1.11, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='shipment',
            name='receiver_zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[shipments.models.zip_code_validator]),
        ),
        migrations.AddField(
            model_name='shipper',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, null=True, validators=[shipments.models.zip_code_validator]),
        ),
    ]
