# Generated by Django 4.2.20 on 2025-06-05 17:23

from django.db import migrations, models
import shipments.models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_chargeable_weight_shipment_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='awb_number',
            field=models.CharField(default=shipments.models.get_default_awb, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Base shipping cost', max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='chargeable_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='price_of_shipment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reference_number',
            field=models.CharField(default=shipments.models.get_default_reference, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='volumetricks',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
    ]
