# Generated by Django 4.2.25 on 2025-10-21 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0003_alter_shipment_awb_number_alter_shipment_base_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='created_by',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
